
import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { BlogPostType } from './blog/types';
import AnimatedSection from './AnimatedSection';
import BlogPost from './blog/BlogPost';

const Blog = () => {
  const { toast } = useToast();
  const [blogPosts, setBlogPosts] = useState<BlogPostType[]>([
    {
      id: '1',
      title: "From Pixels to Production: Figma's New Design-to-Code Feature",
      description: "Exploring how Figma's design-to-code feature is reshaping the workflow between designers and developers.",
      url: 'https://medium.com/@shanlockett/from-pixels-to-production-figmas-new-design-to-code-feature-8f7d25e758ad',
      platform: 'medium',
      date: '2023-12-10T12:00:00Z',
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      alt: "Design interface showing Figma's design-to-code conversion tool"
    },
    {
      id: '2',
      title: 'Unlocking Digital Flexibility: The Transformative Benefits of Headless CMS',
      description: 'A deep dive into how headless CMS architecture provides greater flexibility and scalability for modern digital experiences.',
      url: 'https://medium.com/@shanlockett/unlocking-digital-flexibility-the-transformative-benefits-of-headless-cms-16622a762c69',
      platform: 'medium',
      date: '2023-11-05T12:00:00Z',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      alt: "Abstract digital representation of content management systems architecture"
    },
    {
      id: '3',
      title: 'Balancing a Side Hustle with Full-Time Employment',
      description: 'Practical advice and strategies for managing a side business while maintaining your full-time job commitments.',
      url: 'https://medium.com/@shanlockett/balancing-a-side-hustle-with-full-time-employment-with-example-a60e50b239df',
      platform: 'medium',
      date: '2023-09-20T12:00:00Z',
      image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      alt: "Professional team collaborating on business projects, representing work-life balance"
    },
    {
      id: '4',
      title: 'Kaspa (KAS): An Analysis of Recent Developments',
      description: 'An in-depth look at recent developments in the Kaspa cryptocurrency ecosystem and their potential implications.',
      url: 'https://medium.com/@shanlockett/kaspa-kas-an-analysis-of-recent-developments-f2406ad4561f',
      platform: 'medium',
      date: '2023-08-15T12:00:00Z',
      image: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      alt: "Cryptocurrency market visualization representing Kaspa blockchain technology"
    },
    {
      id: '5',
      title: 'Text-to-Code Generators: The Latest Game Changer in AI',
      description: 'Exploring how text-to-code AI tools are revolutionizing software development and democratizing programming.',
      url: 'https://medium.com/@shanlockett/text-to-code-generators-the-latest-game-changer-in-ai-63f2af9686b4',
      platform: 'medium',
      date: '2023-07-25T12:00:00Z',
      image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      alt: "Computer screen showing code being generated by AI, demonstrating text-to-code technology"
    },
  ]);

  return (
    <section id="blog" className="py-12 md:py-24 border-t border-muted">
      <div className="container-custom">
        <AnimatedSection>
          <h2 className="section-heading">BLOG</h2>
          <p className="text-center text-muted-foreground max-w-3xl mx-auto mb-8 md:mb-12 text-sm md:text-base px-4">
            Check out my latest articles about web development, design, and technology.
            I regularly write on Medium and Substack to share my knowledge and experiences.
          </p>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
            {blogPosts.map((post) => (
              <BlogPost key={post.id} post={post} />
            ))}
          </div>
        </AnimatedSection>
      </div>
    </section>
  );
};

export default Blog;
