// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtnzbigzjoeeseecmkyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0bnpiaWd6am9lZXNlZWNta3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzQ4NzMsImV4cCI6MjA2MDMxMDg3M30.c9gSONI3ipZ0p-bVeMfsfn4uNiNr8mytTM7GwdTbbWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);